### PR TITLE
PvP loading screens

### PR DESCRIPTION
**Pull request by InNoHurryToCode**
## Functionality
PvP map and other data loads, players get stuck in endless matchmaking. Getting back to the main menu from the matchmaking menu works now too.

## Notes
If somebody could figure out what the matchmaking object looks like would be great (the reason it's getting stuck is because I'm returning an array with a null object in it, thus no suitable object is found.). the Get_ActiveProfileStatus() looks interesting, what kind of data does it return?

image

### CODE REVIEW

**Comment by polivilas** [comment]
Here's a slightly older match/join.
`{"err":0,"errmsg":null,"data":[{"profileid":"5ab5622a02153a7da74e50da","status":"MatchWait","sid":"37.61.221.222-17011_PID_09.06.18_07.06.06","ip":"37.61.221.222","port":17011,"version":"bgkidft87ddd","location":"factory4","mode":"deathmatch"}]}`

**Comment by InNoHurryToCode** [comment]
Thanks for your fast reply!

Sadly, no luck so far. I assume it's because the version property doesn't match. The property doesn't make sense to me. For which version of the game is this?

What I've tried on game version 0.11.7.3007 - 0.11.7.3233:
- Changed profileid and location
- Set sid, ip, and port to null (which is done everywhere else) as well.

My attempt can be found here:
```js
case "/client/match/join":
	var matchJoinRequest = JSON.parse(body);
	FinalOutput = JSON.stringify( {"err": 0,"errmsg": null,"data": [ {"profileid": "5c71b934354682353958e984", status:"MatchWait", "sid":"", "ip": "", "port": 0, "version": "bgkidft87ddd", "location": matchJoinRequest.location, "mode": "deathmatch"} ] });
	break;
```

At last, how can I obtain the JSON responses? It would help me implementing other unhandled responses:
```
/client/notifier/channel/create
/client/chatServer/list
/client/queue/status
/client/game/logout
/client/game/profile/nickname/change
```

**Comment by polivilas** [comment]
The responses are from `0.8.5.1359`, the last version before I got banned.
/client/notifier/channel/create - https://pastebin.com/iwvfQs1P
/client/chatServer/list - https://pastebin.com/PbPtTCZf
/client/queue/status - Haven't logged it.
/client/game/logout - Haven't logged it.
/client/game/profile/nickname/change - Haven't logged it.

0.11.7 structures go as follows:
/client/notifier/channel/create - single string, `notifierServer`
/client/chatServer/list - Same as 0.8.5.1359
/client/queue/status - 2 integers, `status`, `position`
/client/game/logout - No response it seems.
/client/game/profile/nickname/change - string `status`, int `NicknameChangeDate`
/client/match/join - string `ProfileId`, string `IpAddress`, int `Port`, string `LocationId`.

**Comment by InNoHurryToCode** [comment]
I have the Edge of Darkness edition, so if you could teach me how to log the responses, I could in return send these to you if you're interested. I could also provide you with a copy of the game when I can afford it.

Thanks for sending the responses, will implement them into the emulator. Getting the ```/client/notifier/channel/create``` to work will stop the game from constantly nagging about it.

**Comment by polivilas** [comment]
My personal setup for 0.8.5 was Proxifier + Charles.
I however would strongly advise against using it on your EoD account as you can and probably will be banned.

**Comment by InNoHurryToCode** [comment]
Once more, thanks for the fast response! I luckily got a separate account, but will need to find a way to avoid accounts with the same IP being banned. 

I got a spare standard edition key, so feel free to use it (which according to the product page gives you access to the closed beta): HW19B-B7EEL-FKG8W-RBP5U

See it as a thank-you for all your hard work, and I secretly hope that it allows you to dump more data. If that ain't the case, then feel free to give the code to someone else who needs it. Got no other friends to play with anyway ;P

**Comment by InNoHurryToCode** [comment]
Alright, ```/client/match/join``` works now on 0.11.7.3287 on factory. Do you have the response for ```/client/getMetricsConfig```?

[edit] Interesting finding: "shortid" is related to the character that is playing. The scav shortid doesn't work for pmc, but the shortid does work on all maps for the scav. The "savage" property in the client request is used to determinate if the player is a scav or pmc. I can send the right shortid based on this.

Will work on fixing this ASAP

**Comment by polivilas** [comment]
Yep! Pushed it with https://github.com/polivilas/EmuTarkov/commit/3b237dba70e62efb9b3710e9a10f3506241d496d
And yeah, I took the key and got a lot of info logged, now features such as 'first profile creation' are within hands reach :] Thank you!

**Comment by InNoHurryToCode** [comment]
Glad I got you back on track. I'm looking forward to see your followup work!

I can't get the PMC shortid to work (the one logged results in bad backend match, can you give it a look?), but the scavid is fully functional.  You can merge this branch and work from there. 

Now that you're working on the PvP side, I can write a lazy queue inplementation for the server ;)

**Comment by polivilas** [comment]
Also, regarding ShortId - It doesn't seem to be used in client anywhere past in the watermark, but I might be wrong.

**Comment by InNoHurryToCode** [comment]
@polivilas interesting, I assume this to be the case too. Sadly, I can't check it myself yet as the connection to the server is lost after metricsConfig is loaded.

**Comment by polivilas** [comment]
Merging this for now, going to investigate more tomorrow.

**Comment by InNoHurryToCode** [comment]
Thanks for merging it, I'm almost done with a simple queue implementation. Good luck for tomorrow.

**Pull request merged**
