### PR TITLE
Scav Randomizer

### PR DESCRIPTION
**Pull request by ghost**
**THIS NEED TO BE VERY TESTED BEFORE MERGING**

Spend a whole day but this is finally almost working
_code is commented as much as I can explain_

Whats new ? :
So each time the game call the server for bots, the script generate many scavs and randomize their inventory
the difference is , the scav can have any Weapon or gear (and sometimes they can be true tank lord)
- randomize stuff, appearance of bots
- weapons is based on preset.json (same as presetTrader)
- each bot had chance to get a facecover, backpacks, helmet, etcc
- each bot spawn with a random Rig (even armored), had one full magazine and a small stack of ammo

Known Issues : 
- checking "Enable Scav Bosses" when creating a game result automatically an infinite loop error at spawn
- sometimes this issue can happened on other maps than factory (especially in horde mode)
- rarely possible but some bots can have no weapons at all and just freeze
- for AKM and variants, bots might have wrong ammo (.366 TKM instead of 7.62) 

Possible and Future improvements : 
- randomize magazine in rig (for the moment its the same mag as the weapon the bot had)
- _PLANNED_ randomize what's inside bags of bots (currently there is nothing)
- generate scav with some sort of  "Seed" randomizer (just like romhacks randomizer)
- randomize weapon mods
- generating scav with real names

-----------------
So if you see some problems, feature to add, optimisations to make, feel free to suggest

### CODE REVIEW

**Comment by ghost** [comment]
i just pushed a second update : )

fixes from previous update : 
- Scav bosses works fine, even if their stuff are fully randomized, their behavior are kinda same 
- infinite loop error looks like fixed, it was weapons who don't have magazines who were the problem , solved it by just adding magazines on presets.json, (didn't change anything on PresetTrader)
- many of unarmed freezing bots are fixed, but still need some testing in case of …
- tested with horde mode, scav bosses etcc look like every map is okay , no error for the moment (I don't say I can't happen)

improvements : 
- in Labs, voices of Bots are PMC voices and not scavs voices ( yep even usec3 works ! )
 
Question : 
- should I Keep the bosses not randomized ?

**Comment by polivilas** [comment]
Something I'm particularly interested in is changing loadouts for specific bot types - for example, game differentiates between sniper and normal assault bots, here, its not the case, leading to sniper bot generation with any weapon and similar problems.

**Comment by panicco** [comment]
Please have a look a maoci fork. This is what I'm working from to build bots specific to the map type. I have allot of experience and have customized his bot creation tool to generate correct bot configs for each map.

**Comment by panicco** [comment]
This idea is something I had aswell to randomly generate bots. The problem I came to was each map needs to have a balance based on bot type so impossible maps like laboratory have harder bots than customs. This is done both by game back end balancing and with the loadouts the bots have. Next step would be for the tool to randomize items in backpack. Currently I'm having unknown errors with certain bots that I'm debugging. 

Realized it is not properly forked from here not sure why. 
https://github.com/themaoci/Enut

It would be good to have a combination. Emutarkov has bypass without file edit
Enut has better folder structure
Emutarkov cleaner inventory
Enut more options.

**Pull request closed without merging**
